spring:
  # ----------------------------------------
  # JPA / Hibernate
  # ----------------------------------------
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

# ----------------------------------------
# Cors
# ----------------------------------------
app:
  cors:
    allowed-origins: "https://sco.hkoikoi.dev, https://www.sco.hkoikoi.dev"

# ----------------------------------------
# Logging
# ----------------------------------------
logging:
  level:
    root: info
    com.hkoikoi.studyroomManager: info
    org.flywaydb: info
